module.exports = {
    DASHBOARD: {
        SET_GENERATE_ADDRESSES_IN_PROCESS: 'SET_GENERATE_ADDRESSES_IN_PROCESS',
        SET_ICO_INFO: 'SET_ICO_INFO',
    },
    TRANSACTION_HISTORY: {
        SET_LOADING_STATUS: 'SET_LOADING_STATUS',
        SET_HISTORY: 'SET_HISTORY',
        CHANGE_SORT: 'CHANGE_SORT',
        SHOW_PAGE_LOADER: 'SHOW_PAGE_LOADER'
    }
};